name: CD-Deploy

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
    - name: Connect SSH server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 5.129.250.92
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt
          if [ -d "django-DefectDojo" ]; then
            rm -rf django-DefectDojo
            echo "Existing project directory removed"
          fi
          sleep 300
          mkdir django-DefectDojo
          echo "New project directory created"
          git clone https://github.com/DefectDojo/django-DefectDojo
          cd django-DefectDojo
          sleep 100
          ./docker/docker-compose-check.sh
          sleep 300
          docker compose build
          
          until docker-compose ps | grep "Up" > /dev/null; do
              sleep 10
          done
          
          docker-compose up -d
          
          until docker compose logs initializer | grep "Admin password:" > /dev/null; do
              sleep 10
          done
          
          docker compose logs initializer | grep "Admin password:"
          
          timeout: 3600s
          
        command_timeout: 10m
        sync: false
        use_insecure_cipher: false
