on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  SERVER_IP: 5.129.250.92
  DEPLOY_USER: root
  key: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  
  deploy:
    name: Deploy to Server
    runs-on: self-hosted
    steps:
      - name: Deploy with docker-compose
        run: |
          git clone https://github.com/DefectDojo/django-DefectDojo
          cd django-DefectDojo
          ./docker/docker-compose-check.sh
          docker compose build
          docker-compose up -d
          docker compose logs initializer | grep "Admin password:"
