name: CD-Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  deploy:
    name: Deploy to Server
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - name: Connect SSH server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 5.129.250.92
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt
          if [ -d "django-DefectDojo" ]; then
            rm -rf django-DefectDojo
            echo "Existing project directory removed"
          fi
          mkdir django-DefectDojo
          echo "New project directory created"
          git clone https://github.com/DefectDojo/django-DefectDojo
          cd django-DefectDojo
          
          ./docker/docker-compose-check.sh

          docker compose build nginx
          
          docker-compose up -d
          
          docker compose logs initializer | grep "Admin password:"
          
