name: CD-Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  deploy:
    name: Deploy to Server
    runs-on: self-hosted-large
    strategy:
      matrix:
        
        include:
          - python-version: "3.11"
            resource-class: large
            
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy DefectDojo
      run: |
        cd /opt
        sudo rm -rf django-DefectDojo
        sudo git clone https://github.com/DefectDojo/django-DefectDojo
        cd django-DefectDojo
        
        sudo chmod +x ./docker/docker-compose-check.sh
        sudo ./docker/docker-compose-check.sh
        
        sudo docker compose build --no-cache
        sudo docker-compose up -d
        
        sleep 90
        sudo docker compose logs initializer | grep -i "admin"
