name: DAST

on: 
  workflow_dispatch:

jobs:
  dast:
    runs-on: self-hosted
    
    steps:
    - name: ZAP Scan
      run: curl -f http://localhost:8080
    
    - name: Run ZAP scan
      run: |
        docker run --rm --network host \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://localhost:8080 \
          -J -r
      continue-on-error: true
